### PR TITLE
Fix signature regex

### LINKED ISSUE #48: JavaScript interpreter error
This is not a duplicate of #44, I've already applied the fix for that. This just started happening to me this evening, and at the same time I'm now getting random 403s with /videoplayback.

```
inv_sig_helper-1  | [2024-12-19T02:26:24Z ERROR inv_sig_helper_rust::jobs] JavaScript interpreter error (sig code): Some(Exception { message: Some("unexpected token in expression: '}'"), file: Some("eval_script"), line: Some(1), column: Some(215), stack: Some("    at eval_script:1:215\n") })
```

I'm glad to hear we will be getting Invidious Companion soon :sweat_smile:

### PR DESCRIPTION
**Pull request by alive4ever**
Fix signature extraction of player `03dbdfad`.

Tested on the `03dbdfad` player.

Both invidious and sig_helper requests to yt have to be from the same public ip address. Otherwise, the player will be denied access to stream data.

Without specifying visitor_data and po_token, the player only gets `medium`, i.e. itag 18 which has both video and audio stream in one media and quality of 360p.

Other formats can be played after configuring visitor_data and po_token.

This pull request is based on the last @unixfox change, so some new commits have to be reverted.

-----

Fixes #48

### CODE REVIEW

**Comment by alive4ever** [comment]
Hi, since this involves reverting some commits, I would like those reverts to be performed by project owner instead of by me and only cherry-pick the last commit from this pull request.

**Comment by techmetx11** [comment]
> Hi, since this involves reverting some commits, I would like those reverts to be performed by project owner instead of by me and only cherry-pick the last commit from this pull request.

I would have to close this PR to do so

**Comment by unixfox** [comment]
@alive4ever what's wrong with that? It's ok to revert the commits here.

**Comment by alive4ever** [comment]
Just giving back the right to revert commits to the project owners if it is desirable to keep the community healthy, i.e. not offending the previous changes.

Feel free to choose whichever works best for the project and the maintainers.

I am fine with either this pull request being closed so project maintainers can perform relevant reverts or this being merged.

**Comment by unixfox** [comment]
Fine with merging as is. I let you handle that @techmetx11 if you are ok with the changes.

**Pull request merged**
