### PR TITLE
Fix REGEX_HELPER_OBJ_NAME

### PR DESCRIPTION
**Pull request by lifo9**
Fixes https://github.com/iv-org/inv_sig_helper/issues/41.
Fixes https://github.com/iv-org/inv_sig_helper/issues/42.

Tested, working.

### CODE REVIEW

**Comment by rockerBOO** [comment]
Tested and working for me as well

**Comment by uncaney** [comment]
hi, can you tell me how you came out to find the fix that issue, i'm trying to radically change how it's managed and make it more resilient to youtube change when regex can't follow up. (moreover where in the /base.js look for errors and what to investigate first when stuff break)

**Comment by lifo9** [comment]
> hi, can you tell me how you came out to find the fix that issue, i'm trying to radically change how it's managed and make it more resilient to youtube change when regex can't follow up. (moreover where in the /base.js look for errors and what to investigate first when stuff break)

Hey,
it would be awesome to make the parser more resilient!
I don't have time to make a proper refactor, so my naive / quick and dirty approach was to:
1. clone the repo and set `RUST_LOG` to `debug` in `docker-compose.yaml`
2. run it with `docker compose up -d`
3. check the logs, error was on [this line](https://github.com/iv-org/inv_sig_helper/blob/23932bfa05397e5dfa2844128f0bee7207aabb0a/src/player.rs#L185).
4. added `debug!("sig function body: {}", sig_function_body);`
5. asked claude 3.5 sonnet to fix the regex - provided `sig_function_body`, current regex and bit more context from the `player.rs` 😆 
6. tested the fix on my instance, it worked -> submitted PR

**Comment by unixfox** [comment]
> hi, can you tell me how you came out to find the fix that issue, i'm trying to radically change how it's managed and make it more resilient to youtube change when regex can't follow up. (moreover where in the /base.js look for errors and what to investigate first when stuff break)

Invidious will soon drop the support for inv sig helper in favor of invidious companion (https://github.com/iv-org/invidious/pull/4985) which includes a built-in decryption system so don't spend all your efforts on this.

**Comment by lifo9** [comment]
> > hi, can you tell me how you came out to find the fix that issue, i'm trying to radically change how it's managed and make it more resilient to youtube change when regex can't follow up. (moreover where in the /base.js look for errors and what to investigate first when stuff break)
> 
> Invidious will soon drop the support for inv sig helper in favor of invidious companion ([iv-org/invidious#4985](https://github.com/iv-org/invidious/pull/4985)) which includes a built-in decryption system so don't spend all your efforts on this.

Awesome news, thank you!

**Pull request merged**
